version: '3'
services:
  app:
    container_name: app
    build: .
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    environment:
      - PORT=4004
    ports:
      - '4004:4004'
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    volumes:
      - ./sql:/var/lib/mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
